[package]
name = "essential-node-db-sql"
version = "0.1.0"
description = "SQL statements for the essential node DB"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
