[package]
name = "essential-node-db-sql"
version = "0.5.0"
description = "SQL statements for the Essential node database"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
