[package]
authors.workspace = true
description = "Derive state from essential protocol"
edition.workspace = true
homepage.workspace = true
name = "essential-node"
repository.workspace = true
version = "0.1.0"

[dependencies]
essential-constraint-asm = { workspace = true, optional = true }
essential-hash = { workspace = true }
essential-node-db = { workspace = true }
essential-relayer = { workspace = true }
essential-state-asm = { workspace = true, optional = true }
essential-types = { workspace = true }
futures = { workspace = true }
num_cpus = { workspace = true }
rusqlite = { workspace = true }
rusqlite-pool = { workspace = true, features = ["tokio"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

[dev-dependencies]
essential-constraint-asm = { workspace = true }
essential-sign = { workspace = true }
essential-state-asm = { workspace = true }
reqwest = { workspace = true }
rusqlite = { workspace = true, features = ["hooks"] }
secp256k1 = { workspace = true }
tracing-subscriber = { workspace = true }
uuid.workspace = true

[features]
default = []
test-utils = [
    "dep:essential-constraint-asm",
    "dep:essential-state-asm",
    "dep:uuid",
]
tracing = ["dep:tracing", "essential-relayer/tracing"]
