[package]
name = "essential-node"
version = "0.1.0"
description = "Derive state from essential protocol"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
essential-hash = { workspace = true }
essential-node-db = { workspace = true }
essential-types = { workspace = true }
futures = { workspace = true }
rusqlite = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true, optional = true } 

[features]
default = []
tracing = ["dep:tracing"]
