[package]
name = "essential-node"
version = "0.1.0"
description = "Derive state from essential protocol"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
essential-constraint-asm = { workspace = true, optional = true }
essential-hash = { workspace = true }
essential-node-db = { workspace = true }
essential-relayer = { workspace = true } # for the error type
essential-state-asm = { workspace = true, optional = true }
essential-types = { workspace = true }
futures = { workspace = true }
num_cpus = { workspace = true }
rusqlite = { workspace = true }
rusqlite-pool = { workspace = true, features = ["tokio"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true, optional = true } 

[dev-dependencies]
essential-sign = { workspace = true }
reqwest = { workspace = true }
secp256k1 = { workspace = true }

[features]
default = []
tracing = ["dep:tracing"]
test-utils = ["dep:essential-constraint-asm", "dep:essential-state-asm"]
