[package]
name = "essential-node"
version = "0.1.0"
description = "Derive state from essential protocol"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true