[package]
name = "essential-node-db"
version = "0.1.0"
description = "Database for essential node"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true