[package]
name = "essential-node-db"
version = "0.1.0"
description = "Database for essential node"
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
essential-hash = { workspace = true }
essential-node-db-sql = { workspace = true }
essential-types = { workspace = true }
postcard = { workspace = true }
rusqlite = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true, features = ["rt"] }

[features]
default = ["async"]
async = ["dep:tokio"]